config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to:'static_pages#help'
  get '/about', to:'static_pages#about' #static_pages_about_urlが使えるようになる
  get '/contact', to:'static_pages#contact'
  get '/signup', to: 'users#new' # 本来は get "/users/new"
  post '/signup', to: 'users#create' # 本来は post "/users/create"
  # get 'sessions/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do # (リスト14.15)
    member do
      get :following, :followers # "/users/:id/following" or"/users/:id/followers"
    end
  end
  resources :users
  resources :microposts, only: [:create, :destroy] # (リスト13.30)
  resources :relationships,       only: [:create, :destroy] # (リスト14.20)
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update] # (リスト12.1)
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token # (リスト 9.3, 11.3, 12.6)
  before_save   :downcase_email
  before_create :create_activation_digest

  has_many :microposts, dependent: :destroy # userとmicropostsは1対多、ユーザーに紐付いたマイクロポストも一緒に削除 (リスト13.11, 13.19)
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy # このuserが能動的関係を持つuserとのRelationship (リスト14.2)
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy # このuserが受動的関係を持つuserとのRelationship (リスト14.12)
  has_many :following, through: :active_relationships, source: :followed # following配列はこのuserにフォローされたuserの集合 (リスト14.8)
  # has_many :followeds, through: :active_relationships # 上はこれでもいいが英文法的に上がふさわしい
  has_many :followers, through: :passive_relationships, source: :follower # followers配列はこのuserをフォローしたuserの集合 (リスト14.12)
  # 上の source: :follower は省略可

  before_save { email.downcase! } # オブジェクトが保存される時点でemail属性を強制的に小文字に変換
  validates :name, presence: true, length: { maximum: 50 } # validates(:name, presence: true) # 空白は無効、長さ制限
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i # メアドの形式を指定
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false }
  has_secure_password # セキュアなパスワードを追加
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true # パスワードは6文字以上、空でもいい(更新時) (リスト10.13)

  class << self # 以下はクラスメソッド (リスト 9.5)
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す (リスト 9.2)
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッションのためにユーザーをデータベースに記憶する (リスト 9.3)
  def remember
    self.remember_token = User.new_token # ランダムな文字列
    update_attribute(:remember_digest, User.digest(remember_token)) # ランダムな文字列をハッシュ化した文字列をremember_digestに保存
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す (リスト 9.6, 11.26)
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil? # そもそもremember_digestが存在しない場合はfalse (リスト 9.19)
    # remember_tokenはcookies[:remember_token]の値
    # remember_tokenは文字列、remember_digestはハッシュ化した文字列
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する (リスト 9.11)
  def forget
    update_attribute(:remember_digest, nil)
  end

  # 試作feedの定義 (リスト13.46)
  # ユーザーのステータスフィードを返す (リスト14.44)
  def feed
    # Micropost.where("user_id = ?", id) # micropostsと本質的に同等、完全な実装は以下 (リスト13.46)
    # Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id) # (リスト14.44)
    # Micropost.where("user_id IN (:following_ids) OR user_id = :user_id",
    #                 following_ids: following_ids, user_id: id) # 上のコードからキーと値のペアを使って修正 (リスト14.46)
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id) # サブクエリを使って処理を効率化 (リスト14.47)
  end

  # (リスト14.10)
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token)) # ランダムなハッシュ値を保存
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  private
    # メールアドレスをすべて小文字にする (リスト 11.3)
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する (リスト 11.3)
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers] # index, edit, update, destroyの前に実行　(リスト10.15, 14.25)
  before_action :correct_user,   only: [:edit, :update] # edit, updateの前に実行　(リスト10.25)
  before_action :admin_user,     only: :destroy # (リスト10.59)

  # (リスト10.35)
  def index
    @users = User.paginate(page: params[:page]) # paginate(page: "ページ数")：デフォルトで30人ずつ取得 (リスト10.46) # @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page]) # (リスト13.23)
  end

  def new # new(作成ページ) → create(作成処理)
    @user = User.new
  end

  def create
    @user = User.new(user_params) # params[:user]
    if @user.save
      # log_in @user # ユーザー登録時にログインも済ませる
      # flash[:success] = "Welcome to the Sample App!" # (リスト7.29)
      # redirect_to @user # redirect_to user_url(@user)と等価
      # (リスト 11.23)
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new' #views/userのnewファイルを呼び出す
    end
  end

  def edit # edit(更新ページ) → update(更新処理)
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy # (リスト10.58)
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  # (リスト14.25)
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow' # show_follow.html.erbというビューを明示的に呼び出す
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow' # show_follow.html.erbというビューを明示的に呼び出す
  end

  private # 外部から使えないようにする
    def user_params # マスアサインメントの脆弱性を防止
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation) # ※admin以外を許可する
    end

    # beforeアクション

    # 正しいユーザーかどうか確認 (リスト10.25)
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) # アクセスされたページのユーザー(@user)がログインユーザー(current_user)と一致しているか (リスト10.28)
    end

    # 管理者かどうか確認 (リスト10.59)
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%# ユーザーをフォローするフォーム (リスト14.21) %>
<%= form_for(current_user.active_relationships.build) do |f| %> <%#  remote: true → Ajax (リスト14.34) %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<%# フォロー/フォロー解除フォーム (リスト14.19) %>
<% unless current_user?(@user) %> <%# 自分以外のユーザーに対してフォームを表示する %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>  <%# フォローしている場合はunfollow、フォローしていない場合はfollowを表示 %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %> <%# @user.new_record? は true → post、false → patch %> <%# "/signup"にpost or /users/:idにpatch %>
  <%= render 'shared/error_messages', object: f.object %> <%# エラーがあるときはエラーを表示 (リスト13.43) %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%# ユーザーをフォロー解除するフォーム (リスト14.22) %>
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %> <%# remote: true → Ajax (リスト14.35) %>
  <%= f.submit "Unfollow", class: "btn btn-default" %>
<% end %>

app/views/users/_user.html.erb
<%# (リスト10.51) %>
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <%# 管理ユーザーにのみdeleteリンクを表示 (リスト10.57) %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Save changes") %>
<% provide(:url, user_path) %> <%# /users/:id %>

<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a> <%# target="_blank"：リンク先を新しいタブで開く、noopener：セキュリティ対策 %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%# (リスト10.37) %>
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %> <%# (リスト10.45) %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render @users %> <%# (リスト10.50, 10.52) %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<% provide(:url, signup_path) %> <%# /signup %>

<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>, <%= @user.created_at %>, <%= @user.updated_at %>, <%= Time.now %>

<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %> <%# フォロワーの統計情報 (リスト14.23) %>
    </section>
  </aside>
  <%# リスト 13.24 %>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %> <%# フォロー/フォロー解除フォーム (リスト14.23) %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %> <%# _micropost.html.erbを読み込み %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<%# フォロー/フォロワーの両方を表示 (リスト14.26) %>
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>